// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCviLPeHYddckSY4DSDpUmxZISuozoLVdY',
    appId: '1:567150128842:android:1fd6bc03645afd625e0e33',
    messagingSenderId: '567150128842',
    projectId: 'serenemind-a9b00',
    storageBucket: 'serenemind-a9b00.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNdYqkuJgSmpzXGNzwIKDCr0fv27nOzow',
    appId: '1:567150128842:ios:0253f2c60a3a12495e0e33',
    messagingSenderId: '567150128842',
    projectId: 'serenemind-a9b00',
    storageBucket: 'serenemind-a9b00.firebasestorage.app',
    androidClientId: '567150128842-d97c3hkvl2drrmknt9n3v56p2dll6nos.apps.googleusercontent.com',
    iosClientId: '567150128842-tcnmt51nvha7quaiu3rm1hiltahp2o1m.apps.googleusercontent.com',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDqb0pt02_6qDQSPDUyRVy2WnxONR63DvM',
    appId: '1:567150128842:web:171045d3c295c03f5e0e33',
    messagingSenderId: '567150128842',
    projectId: 'serenemind-a9b00',
    authDomain: 'serenemind-a9b00.firebaseapp.com',
    storageBucket: 'serenemind-a9b00.firebasestorage.app',
    measurementId: 'G-3Z0ZW14BP9',
  );

}